config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"


  devise_for :users
  resources :board
  resources :team do
    resources :task
    resources :unit
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 

  
end

app/controllers/unit_controller.rb
class UnitController < ApplicationController
    load_and_authorize_resource
    before_action :authenticate_user!
    before_action :set_team

    def index
        @units = @current_team.unities.all()
        respond_to do |format|
            format.js { render action: "index" }
        end
    end


    def new
        @unit = Unity.new
        respond_to do |format|
            format.js {render action: "new" }
        end
    end


   

    def update
        @unit = Unity.find(params[:id])
        @unit.role = Role.find(params[:role_id])
        @units = @current_team.unities.all()
        respond_to do |format|
        if @unit.save()
            format.js {render action: "index" }
         else
            format.js   {  render  "shared/alert", :locals=>{:alert=>"Something went wrong"} }
         end
        end

    end


    def create
        @user =  nil;
        if(params.has_key?(:email))
            @user = User.where(email: params[:email]).first()
        end

        @unit = Unity.new()
        @unit.team = @current_team
        @unit.user = @user
        @unit.role = Role.where(name: 'user').first()
        @units =   @current_team.unities.all()
        respond_to do |format|
        if @unit.save
            format.js {render action: "index" }
            format.html {redirect_to root_path,  notice:"New task added"}
            format.json { render json: @unit.to_json }
            else
            format.js {render action: "index" }
            format.html {redirect_to root_path,  notice:"Error"}
            format.json { render json: @unit.to_json }
          end
        end
    end


    def destroy
        @unit = Unity.find(params[:id])
        @units =   @current_team.unities.all()
        @unit.destroy();
        respond_to do |format|
                format.js {render action: "index" }
                format.html {redirect_to root_path,  notice:"User removed"}
         end
    end


    private

    def set_team
        @current_team = Team.find(params[:team_id])
    end


  

end

app/helpers/unit_helper.rb
module UnitHelper
end

app/views/unit/_new.html.erb
<div id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Add new user </h4>
                </div>
                <%= form_for @unit, url: {action:"create"},:class=>"form-horizontal",:remote=>true  do |f|  %>
                <div class="modal-body">
                        <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"></span>
                                <%= email_field_tag :email,nil,  class:"form-control",placeholder:"Email" %>
                            </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= f.submit "Add",:class=>"btn btn-primary" %>
                </div>
                <% end %>
            </div>
        </div>
</div>

app/views/unit/_units.html.erb
<div class="container" >
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header" >
                    <div class="HeaderName">Users  belong to <%= @current_team.name %> </div>
                     <% if current_user.isCreator?(@current_team) %>
                     <small class="text-info"> <%= fa_icon "plus" %> <%= link_to "Add new user",new_team_unit_url(@current_team), remote: true %>  </small>
                     <% end %>
                     <div><small class="text-info"> <%= fa_icon "arrow-left" %> <%= link_to "Back to teams board",board_index_url %>  </small></div>
          </h1>
            </div>
        </div>
</div>

    <div class="container" id="ContentContainer">
            <div class="flex-row row"  id="teams">
                          <ul class="list-group" style="width:100%;">
                    <% @units.each do |unit| %>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                 <%= unit.user.email %> - <%= unit.user.username %> 
                                 <% if current_user.isCreator?(@current_team) %>
                            <div class="pull-right action-buttons">
                                    <%= select_tag "" + unit.id.to_s  , options_for_select(Role.all().collect{ |u| [u.name, u.id]}, :selected=>unit.role.id),{:class=>"Role"} %>
                                    <%= link_to team_unit_path(@current_team,unit), method: :delete, remote: true do %>
                                    <%=fa_icon "trash" %>
                                    <% end %>
                            </div>
                            <% end %>
                            </li>
                        <% end %>
                    </ul>
            </div>
        </div>  

<script>
        $('.Role').on('change', function(){
            var  id =  $(this).attr("id");
            $.ajax({ 
                beforeSend: function(xhr) {
        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
      }, 
               type: "PUT",
               url: "/team/<%= @current_team.id  %>/unit/" + id ,
               data: { role_id: $('option:selected', this).val() }
            }).done(function(data) {
              console.log(data);
            });
          });
 </script>

app/views/unit/index.js.erb
$('#myModal').remove()
$('.modal-backdrop').remove();
$('.content').empty();
$('.content').append("<%= j render :partial => 'units' %>");

app/views/unit/new.js.erb
$('#myModal').remove()
$(".container").append("<%= j render :partial => 'new' %>");
$("#myModal").modal('show');