config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"


  devise_for :users
  resources :board
  resources :team do
    resources :task
    resources :unit
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 

  
end

app/models/task.rb
class Task < ApplicationRecord
       
    belongs_to :team
    belongs_to :user_created, :class_name => "User"
    belongs_to :user_finish, :class_name => "User", required: false
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
    load_and_authorize_resource
    before_action :authenticate_user!
    before_action :set_team

    def index
    @tasks =  @current_team.tasks.all()
    respond_to do |format|
        format.js { render action: "index" }
    end
    end

    def create
        @task = Task.new(task_params)
        @task.user_created = current_user
        @task.team = @current_team
        @tasks =  @current_team.tasks.all()
        respond_to do |format|
        if @task.save
            format.js {render action: "index" }
            format.html {redirect_to root_path,  notice:"New task added"}
            format.json { render json: @task.to_json }
            else
            format.js   {  render  "shared/alert", :locals=>{:alert=>"Something went wrong"} }
            format.html {redirect_to root_path,  notice:"Error"}
            format.json { render json: @task.to_json }
          end
        end

    end

    def destroy
        @task = Task.find(params[:id])
        @tasks =  @current_team.tasks.all()
        @task.destroy();
        respond_to do |format|
                format.js {render action: "index" }
                format.html {redirect_to root_path,  notice:"Task removed"}
         end
    end

    def update
        @task = Task.find(params[:id])
        @tasks =  @current_team.tasks.all()
        respond_to do |format|
            if @task.update(task_params)
                format.js {render action: "index" }
                format.html {redirect_to root_path,  notice:"Task updated"}
                format.json { render json: @task.to_json }
            else
                format.js {render action: "index" }
                format.html {redirect_to root_path,  notice:"Error"}
                format.json { render json: @task.to_json }
            end
         end
     end


    def new
        @task = Task.new
        respond_to do |format|
            format.js {render action: "new" }
        end
    end
    
    private

    def set_team
       @current_team = Team.find(params[:team_id])
    end

    def task_params
        params.require(:task).permit(:name,:finish)
    end


end

app/helpers/tasks_helper.rb
module TasksHelper

    def task_state(boolean)
        boolean ? '<%= fa_icon "check-square" %>' : '<%= fa_icon "square" %>'
    end

end

app/views/task/_new.html.erb
<div id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Create new task </h4>
                </div>
                <%= form_for @task, url: {action:"create"},:class=>"form-horizontal",:remote=>true  do |f|  %>
                <div class="modal-body">
                        <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"></span>
                                <%= f.text_field :name, placeholder: "Task name", autofocus: true ,  :class=>"form-control" %>
                            </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= f.submit "Create",:class=>"btn btn-primary" %>
                </div>
                <% end %>
            </div>
        </div>
</div>

app/views/task/_tasks.html.erb
<div class="container" >
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header" >
                    <div class="HeaderName">The tasks  belong to <%= @current_team.name %> </div>
                    <% if current_user.isCreator?(@current_team) || current_user.isUser?(@current_team)  %>
                     <small class="text-info"> <%= fa_icon "plus" %> <%= link_to "Create new task",new_team_task_url(@current_team), remote: true %>  </small>
                     <% end %>
                     <div><small class="text-info"> <%= fa_icon "arrow-left" %> <%= link_to "Back to teams board",board_index_url %>  </small></div>
          </h1>
            </div>
        </div>
</div>

    <div class="container" id="ContentContainer">
            <div class="flex-row row"  id="teams">
                          <ul class="list-group" style="width:100%;">
                            <% @tasks.each do |task| %>
                            <li class="list-group-item d-flex justify-content-between align-items-center <%= task.finish ? 'task-done' : ' ' %>">
                            <%= task.name %>
                            <div class="pull-right action-buttons">
                                    <% if current_user.isCreator?(@current_team) || current_user.isUser?(@current_team)  %>
                             <%= link_to team_task_path(@current_team,task, task: {finish: !task.finish}), method: :put, remote: true do %>
                             <% if task.finish == true %>
                             <%= fa_icon "check-square" %>
                            <%else %>
                            <%= fa_icon "square" %>
                            <% end %>
                             <% end %> 
                             <%= link_to team_task_path(@current_team,task), method: :delete, remote: true do %>
                             <%=fa_icon "trash" %>
                             <% end %>
                            </div>
                            </li>
                        <% end %>
                        <% end %>
                    </ul>
            </div>
        </div>  

app/views/task/index.js.erb
$('#myModal').remove()
$('.modal-backdrop').remove();
$('.content').empty();
$('.content').append("<%= j render :partial => 'tasks' %>");