config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"


  devise_for :users
  resources :board
  resources :team do
    resources :task
    resources :unit
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 

  
end

app/models/team.rb
class Team < ApplicationRecord

    cattr_accessor :current 

    
    has_many :unities
    has_many :users, through: :unities
    has_many :tasks
    has_many :roles, through: :unities

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    load_and_authorize_resource
    before_action :authenticate_user!
def new
    @team = Team.new
    respond_to do |format|
        format.js {render action: "new" }
    end
end

def create
    @team = Team.new(team_params)
    @unit = Unity.new
    @unit.role = Role.where(name: 'creator').first()
    respond_to do |format|
    if @team.save
        @unit.user = current_user
        @unit.team = @team
        @unit.save
        format.js {render action: "create" }
        format.html {redirect_to root_path,  notice:"New team added"}
        format.json { render json: @team.to_json }
        else
        format.js   {  render  "shared/alert", :locals=>{:alert=>"Something went wrong"} }
        format.html {redirect_to root_path,  notice:"Error"}
        format.json { render json: @team.to_json }
      end
    end
end

def destroy
    @team = Team.find(params[:id])
    @team.destroy
    respond_to do |format|
        format.html { redirect_to  root_path, notice: 'Team was successfully destroyed.' }
        format.js { render action: "destroy" }
    
     end 
end

private


def team_params
   params.require(:team).permit(:name,:description)
end


end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/team/_new.html.erb
<div id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Create new team </h4>
                </div>
                
                <%= form_for @team, url: {action:"create"},:class=>"form-horizontal",:remote=>true  do |f|  %>
                <div class="modal-body">
                        <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"></span>
                                <%= f.text_field :name, placeholder: "Team name", autofocus: true ,  :class=>"form-control" %>
                            </div>
                            <div style="margin-bottom: 25px" class="input-group">
                                    <span class="input-group-addon"></span>
                                    <%= f.text_field :description, placeholder: "Description", autofocus: true ,  :class=>"form-control" %>
                                </div>
                         
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= f.submit "Create",:class=>"btn btn-primary" %>
                </div>
                <% end %>
            </div>
        </div>
</div>

app/views/team/_single.html.erb
<div class="col-xs-6 col-sm-4 col-lg-3" id="team_<%= team.id %>" >
        <div class="thumbnail" >
            <div class="caption">
                    <% if @current_user.isCreator?(team) %>
                    <div class="text-right">
                    <%= link_to  team_unit_index_url(team),:remote=>true  do %>
                    <%= fa_icon "user" %> 
                     <% end %>
                    </div>
                    <% end %>
                    <div class="text-center">
                <h3><%= team.name %></h2>
                <p class="flex-text text-muted"> <%= team.description %>  </p>
                    </div>
                <%= link_to  "Show tasks",  team_task_index_url(team),:class=>"btn btn-primary",:remote=>true %>
                <% if @current_user.isCreator?(team) %>
                <%= link_to  "Remove", team_url(team),method: :delete,:class=>"btn btn-danger",:style=>"margin-top:10px;",:remote=>true %>
                <% end %>
            </div>
        </div>
    </div>

app/views/team/create.js.erb
$('#myModal').remove()
$('.modal-backdrop').remove();
$('#teams').append("<%= j render :partial => 'single', locals: {team: @team} %>");

app/views/team/destroy.js.erb
$('#team_<%=@team.id %>').remove();

app/views/team/new.js.erb
$('#myModal').remove()
$(".container").append("<%= j render :partial => 'new' %>");
$("#myModal").modal('show');